export const jsonResponse = {
  "request": {
    "country": "uk",
    "language": "en",
    "location": "london",
    "num_res": "20",
    "offset": 0,
    "output": "json_xs",
    "page": 1,
    "pretty": "1",
    "product_type": "realestate",
    "property_type": "property",
    "size_type": "net",
    "size_unit": "m2",
    "sort": "nestoria_rank",
    "listing_type": "buy"
  },
  "response": {
    "application_response_code": "100",
    "application_response_text": "listings returned for one unambiguous location",
    "attribution": {
      "img_height": 22,
      "img_url": "https://resources.nestimg.com/nestoria/img/pbr_v1.png",
      "img_width": 183,
      "link_to_img": "http://www.nestoria.com"
    },
    "created_http": "Fri, 07 Jul 2017 09:33:20 GMT",
    "created_unix": 1499420000,
    "link_to_url": "https://www.nestoria.co.uk/london/property/buy",
    "listings": [
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 238,
        "img_url": "https://imgs.nestimg.com/london_107327135413807136.jpg",
        "img_width": 317,
        "keywords": "En suite, Penthouse, No Chain, Balcony, Refurbished, Double Bedroom, Kitchen, Lift, Off Street Parking, Basement, Reception",
        "latitude": 51.52485,
        "lister_name": "Currell",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107327135413807136/title/5/1-1?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.089672,
        "price": 1550000,
        "price_currency": "£",
        "price_formatted": "£1,550,000",
        "price_high": 1550000,
        "price_low": 1550000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Key features: duplex penthouse apartment with sensational city view...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/london_107327135413807136.jpg",
        "thumb_width": 80,
        "title": "Featherstone Street, London EC1Y",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "PrimeLocation",
        "img_height": 192,
        "img_url": "https://imgs.nestimg.com/flat_london_107327169636247721.jpg",
        "img_width": 256,
        "keywords": "Share of Freehold, Garden, En suite, Balcony, Double Bedroom, Kitchen, Lift, Porter, Modern, Reception",
        "latitude": 51.51062,
        "lister_name": "Hamptons",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107327169636247721/title/5/1-2?serpUid=&pt=1&ot=1&l=london&did=69_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.096176,
        "price": 825000,
        "price_currency": "£",
        "price_formatted": "£825,000",
        "price_high": 825000,
        "price_low": 825000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "This ly presented two double bedroom apartment is set on the second...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107327169636247721.jpg",
        "thumb_width": 80,
        "title": "Globe View, 10 High Timber Street, City Of London EC4V",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 236,
        "img_url": "https://imgs.nestimg.com/flat_london_106850639293646295.jpg",
        "img_width": 314,
        "keywords": "Garden, En suite, Gym, Sauna, Wood Floor, Double Bedroom, Kitchen, Porter, Swimming Pool, Reception",
        "latitude": 51.507645,
        "lister_name": "Mylondonhome",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000106850639293646295/title/5/1-3?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.107208,
        "price": 2000000,
        "price_currency": "£",
        "price_formatted": "£2,000,000",
        "price_high": 2000000,
        "price_low": 2000000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Views of london's iconic skyline including the london eye, the oxo ...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_106850639293646295.jpg",
        "thumb_width": 80,
        "title": "South Bank Tower, 55 Upper Ground, Southwark, London SE1",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "PrimeLocation",
        "img_height": 221,
        "img_url": "https://imgs.nestimg.com/flat_london_107197070841737073.jpg",
        "img_width": 294,
        "keywords": "Garden, En suite, Gym, Sauna, Wood Floor, Double Bedroom, Kitchen, Porter, Swimming Pool, Reception",
        "latitude": 51.507645,
        "lister_name": "Mylondonhome",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107197070841737073/title/5/1-4?serpUid=&pt=1&ot=1&l=london&did=69_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.107208,
        "price": 1895000,
        "price_currency": "£",
        "price_formatted": "£1,895,000",
        "price_high": 1895000,
        "price_low": 1895000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "This 15th floor two bedroom apartment situated on the north west si...",
        "thumb_height": 59,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107197070841737073.jpg",
        "thumb_width": 80,
        "title": "Southbank Tower, 55 Upper Ground, London SE1",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 255,
        "img_url": "https://imgs.nestimg.com/flat_london_106850636758432023.jpg",
        "img_width": 340,
        "keywords": "Balcony, Fireplace, High Ceilings, Wood Floor, Double Bedroom, Kitchen, Lift, Porter, Dishwasher, Modern, Reception, Edwardian, Gas Central Heating",
        "latitude": 51.523632,
        "lister_name": "Victorstone",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000106850636758432023/title/5/1-5?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.159133,
        "price": 1550000,
        "price_currency": "£",
        "price_formatted": "£1,550,000",
        "price_high": 1550000,
        "price_low": 1550000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Moments from regents park in the heart of marylebone is this modern...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_106850636758432023.jpg",
        "thumb_width": 80,
        "title": "Glentworth Street, Marylebone, London NW1",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 1,
        "bedroom_number": 1,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 245,
        "img_url": "https://imgs.nestimg.com/flat_london_107196947916104018.jpg",
        "img_width": 326,
        "keywords": "Leasehold, High Ceilings, Wood Floor, Double Bedroom, Kitchen, Modern, Shared Equity, Reception",
        "latitude": 51.530888,
        "lister_name": "Ellis",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107196947916104018/title/5/1-6?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.082066,
        "price": 550000,
        "price_currency": "£",
        "price_formatted": "£550,000",
        "price_high": 550000,
        "price_low": 550000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Government help to buy scheme eliigible! Ly presented and finished ...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107196947916104018.jpg",
        "thumb_width": 80,
        "title": "The Residence Hoxton, London N1",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 1,
        "bedroom_number": 1,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 255,
        "img_url": "https://imgs.nestimg.com/flat_london_106936999140564018.jpg",
        "img_width": 340,
        "keywords": "Leasehold, High Ceilings, Wood Floor, Double Bedroom, Kitchen, Modern, Shared Equity, Reception",
        "latitude": 51.530888,
        "lister_name": "Ellis",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000106936999140564018/title/5/1-7?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.082066,
        "price": 580000,
        "price_currency": "£",
        "price_formatted": "£580,000",
        "price_high": 580000,
        "price_low": 580000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Help to buy eligible only 3 x 1 beds available ly presented and fin...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_106936999140564018.jpg",
        "thumb_width": 80,
        "title": "The Residence Hoxton, London N1",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 1,
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "PrimeLocation",
        "img_height": 236,
        "img_url": "https://imgs.nestimg.com/semi_detached_london_107327184576544159.jpg",
        "img_width": 314,
        "keywords": "Freehold, Garden, Fireplace, High Ceilings, Raised Ground, Wood Floor, Double Bedroom, Kitchen, Patio, Reception",
        "latitude": 51.539387,
        "lister_name": "Purplebricks",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107327184576544159/title/5/1-8?serpUid=&pt=1&ot=1&l=london&did=69_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.065803,
        "price": 1325000,
        "price_currency": "£",
        "price_formatted": "£1,325,000",
        "price_high": 1325000,
        "price_low": 1325000,
        "price_type": "fixed",
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "A rarely available freehold period house offered for sale on one of...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/semi_detached_london_107327184576544159.jpg",
        "thumb_width": 80,
        "title": "Albion Drive, London Fields E8",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 255,
        "img_url": "https://imgs.nestimg.com/flat_london_107134980557808783.jpg",
        "img_width": 340,
        "keywords": "En suite, Grade II, Balcony, Conversion, Wood Floor, Double Bedroom, Kitchen, Off Street Parking, Porter, Modern, Reception, Listed",
        "latitude": 51.503464,
        "lister_name": "Purplebricks",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107134980557808783/title/5/1-9?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.060379,
        "price": 800000,
        "price_currency": "£",
        "price_formatted": "£800,000",
        "price_high": 800000,
        "price_low": 800000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Guide price 800,000 825,000 a sensational two double bedroom wareho...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107134980557808783.jpg",
        "thumb_width": 80,
        "title": "Wapping High Street, London E1W",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 1,
        "bedroom_number": 1,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 255,
        "img_url": "https://imgs.nestimg.com/flat_london_107327131355903168.jpg",
        "img_width": 340,
        "keywords": "Garden, Fireplace, High Ceilings, Refurbished, Wood Floor, Kitchen, Modern, Patio, Cellar, Reception",
        "latitude": 51.55474,
        "lister_name": "Anthony Pepe",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107327131355903168/title/5/1-10?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.093483,
        "price": 580000,
        "price_currency": "£",
        "price_formatted": "£580,000",
        "price_high": 580000,
        "price_low": 580000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "A large one bedroom apartment that has been refurbished to a high s...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107327131355903168.jpg",
        "thumb_width": 80,
        "title": "Stradbroke Road, Highbury, London N5",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 184,
        "img_url": "https://imgs.nestimg.com/flat_london_106801061933556658.jpg",
        "img_width": 245,
        "keywords": "Kitchen, Lift, Modern, Parking, Georgian",
        "latitude": 51.529533,
        "lister_name": "House Simple",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000106801061933556658/title/5/1-11?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.114562,
        "price": 950000,
        "price_currency": "£",
        "price_formatted": "£950,000",
        "price_high": 950000,
        "price_low": 950000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Large 2 bedroom 2 bathroom flat in london. Percy circus is a histor...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_106801061933556658.jpg",
        "thumb_width": 80,
        "title": "Percy Circus, London WC1X - Modern",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 3,
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 255,
        "img_url": "https://imgs.nestimg.com/terraced_london_106955302791477955.jpg",
        "img_width": 340,
        "keywords": "Freehold, Garden, Grade II, Fireplace, Terraced, Kitchen, Patio, Reception, Georgian, Listed",
        "latitude": 51.50491,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000106955302791477955/title/5/1-12?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.110002,
        "price": 1399950,
        "price_currency": "£",
        "price_formatted": "£1,399,950",
        "price_high": 1399950,
        "price_low": 1399950,
        "price_type": "fixed",
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "A opportunity to purchase a striking period three bedroom house for...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/terraced_london_106955302791477955.jpg",
        "thumb_width": 80,
        "title": "Whittlesey Street, London SE1 - Patio",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "PrimeLocation",
        "img_height": 166,
        "img_url": "https://imgs.nestimg.com/flat_london_107116029575615380.jpg",
        "img_width": 221,
        "keywords": "En suite, Refurbished, Double Bedroom, Kitchen, Porter, Parking, Reception",
        "latitude": 51.54014,
        "lister_name": "Hamptons",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107116029575615380/title/5/1-13?serpUid=&pt=1&ot=1&l=london&did=69_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.096357,
        "price": 650000,
        "price_currency": "£",
        "price_formatted": "£650,000",
        "price_high": 650000,
        "price_low": 650000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "A two bedroom lateral flat located in a sought after development op...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107116029575615380.jpg",
        "thumb_width": 80,
        "title": "Melville Place, London N1 - Reception",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 1,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 255,
        "img_url": "https://imgs.nestimg.com/flat_london_106781879011225730.jpg",
        "img_width": 340,
        "keywords": "Garden, Maisonette, Fireplace, High Ceilings, Raised Ground, Wood Floor, Double Bedroom, Kitchen, Modern, Reception",
        "latitude": 51.539642,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000106781879011225730/title/5/1-14?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.140476,
        "price": 815000,
        "price_currency": "£",
        "price_formatted": "£815,000",
        "price_high": 815000,
        "price_low": 815000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "The property comprises a dual aspect kitchen and reception room on ...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_106781879011225730.jpg",
        "thumb_width": 80,
        "title": "Greenland Road, London NW1 - Modern",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 1,
        "bedroom_number": 1,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 241,
        "img_url": "https://imgs.nestimg.com/flat_london_107327133788311926.jpg",
        "img_width": 321,
        "keywords": "Leasehold, Garden, No Chain, Conversion, Fireplace, Wood Floor, Kitchen, Reception",
        "latitude": 51.54552,
        "lister_name": "Mchugh",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107327133788311926/title/5/1-15?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.128554,
        "price": 625000,
        "price_currency": "£",
        "price_formatted": "£625,000",
        "price_high": 625000,
        "price_low": 625000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "A ly bright & ly proportioned one bedroom garden flat, set on the g...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107327133788311926.jpg",
        "thumb_width": 80,
        "title": "St. Augustines Road, Camden Town, London NW1",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 255,
        "img_url": "https://imgs.nestimg.com/flat_london_107253227147988196.jpg",
        "img_width": 340,
        "keywords": "Leasehold, Shared Garden, Balcony, Porter, Reception",
        "latitude": 51.518646,
        "lister_name": "Property Inside London",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107253227147988196/title/5/1-16?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.100324,
        "price": 1400000,
        "price_currency": "£",
        "price_formatted": "£1,400,000",
        "price_high": 1400000,
        "price_low": 1400000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "A premium unit being offered at a discount to the current list pric...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107253227147988196.jpg",
        "thumb_width": 80,
        "title": "Askew House, Barts Square, West Smithfield, London EC1A",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 1,
        "bedroom_number": 4,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 189,
        "img_url": "https://imgs.nestimg.com/flat_london_107327138997965055.jpg",
        "img_width": 252,
        "keywords": "Balcony, Purpose Built, Wood Floor, Double Bedroom, Kitchen, Reception, Gas Central Heating",
        "latitude": 51.52957,
        "lister_name": "Victorstone",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107327138997965055/title/5/1-17?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.140122,
        "price": 599950,
        "price_currency": "£",
        "price_formatted": "£599,950",
        "price_high": 599950,
        "price_low": 599950,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "A well presented four double bedroom apartment situated on the sixt...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107327138997965055.jpg",
        "thumb_width": 80,
        "title": "Stanhope Street, Camden, London NW1",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 237,
        "img_url": "https://imgs.nestimg.com/flat_london_106795229099592282.jpg",
        "img_width": 316,
        "keywords": "Leasehold, En suite, Double Bedroom, Kitchen, Lift, Swimming Pool, Parking, Reception",
        "latitude": 51.507645,
        "lister_name": "Coldwell Banker",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000106795229099592282/title/5/1-18?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.107208,
        "price": 1870000,
        "price_currency": "£",
        "price_formatted": "£1,870,000",
        "price_high": 1870000,
        "price_low": 1870000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "A 2 bedroom, 2 bathroom apartment is now available for sale on the ...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_106795229099592282.jpg",
        "thumb_width": 80,
        "title": "Upper Ground SE1, London, - Reception",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 216,
        "img_url": "https://imgs.nestimg.com/flat_london_107327133758986678.jpg",
        "img_width": 288,
        "keywords": "En suite, No Chain, Balcony, Double Bedroom, Kitchen, Modern, Reception",
        "latitude": 51.522293,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107327133758986678/title/5/1-19?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.075191,
        "price": 645000,
        "price_currency": "£",
        "price_formatted": "£645,000",
        "price_high": 645000,
        "price_low": 645000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "A two bedroom apartment on the second floor of this modern developm...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107327133758986678.jpg",
        "thumb_width": 80,
        "title": "Quaker Street, London E1 - Modern",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      },
      {
        "bathroom_number": 1,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "Zoopla",
        "img_height": 255,
        "img_url": "https://imgs.nestimg.com/flat_london_107295221485093154.jpg",
        "img_width": 340,
        "keywords": "Share of Freehold, Garden, Grade II, No Chain, Victorian, Double Bedroom, Basement, Listed",
        "latitude": 51.557983,
        "lister_name": "Anthony Pepe",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000107295221485093154/title/5/1-20?serpUid=&pt=1&ot=1&l=london&did=57_default&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -0.1017,
        "price": 635000,
        "price_currency": "£",
        "price_formatted": "£635,000",
        "price_high": 635000,
        "price_low": 635000,
        "price_type": "fixed",
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Two double bedrooms and a private garden make this property a rare ...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/flat_london_107295221485093154.jpg",
        "thumb_width": 80,
        "title": "Avenell Road, Highbury, London N5",
        "updated_in_days": 0,
        "updated_in_days_formatted": "new!"
      }
    ],
    "locations": [
      {
        "center_lat": 51.527243,
        "center_long": -0.106841,
        "long_title": "London",
        "place_name": "london",
        "title": "London"
      }
    ],
    "page": 1,
    "sort": "nestoria_rank",
    "status_code": "200",
    "status_text": "OK",
    "thanks": "For using the Nestoria API.",
    "total_pages": 4650,
    "total_results": 93001,
    "listing_type": "buy"
  }
}